controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1111ffffffffffffffffffff1111111111ffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111111111ffff1111111111fff11111111111111fffffffffffff
    ffffffffffffffffffffffaaaafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11111111111aaa1111111111fff1111111111fff1111111111111111fffffffffff
    fffffffffffffffffffffaaaaaaffffffffffffffffffffffffffffffffffff111111111111111fffffffffffffff11111111111aaa111ff111111ff1111111111fff111ffffff1111111fffffffffff
    fffffffffffffffffffffaaaaaaffaaffffffffffffffffffffffffffffff11111111111111111fffffffffffffff11111111111aaa111faa111111f1111fffffffff111fffffffff1111fffffffffff
    ffffffffffffffffffaaaa111111111111111ff1111111111fffff11111ff11111111111111111fff111ffffffffffff111faaaaaaa111aaaa11111f1111fffffffff111ffffffffff111fffffffffff
    fffffffffffffffffaaaaa111111111111111ff1111111111fffff11111ff1111fffffffffffffff1111ffff111fffff111aaaaaaaa111aaaaa1111f1111fffffffff111ffffffffff111fffffffffff
    ffffffffffffffffaaaaaa111111111111111ff1111111111fffff11111ff111ffffffffffffffff1111ffff111fffff111aaaaaaaa1111aaaaa111ff111fffffffff111ffffffffff111fffffffffff
    ffffffffffffffffaaaaaa111aaaaaaaaa111ff111ffffffffffff11111ff111ffffffffffffffff1111ffff111fffff111aaaaaaaa1111aaaaa111ff111fffffffff111ffffffffff111fffffffffff
    fffffffffffffffffaaaaa111aaaaaaaaa111ff111ffffffffffff11111ff111ffffffffffffffff11111fff111fffff1111aaaaaaaa111aaaaa111ff111fffffffff111111111fff1111fffffffffff
    fffffffffffffaaaa9aaaa111aaaaaaaaa111fa111affffffffffffffffff111ffffffffffffffff11111fff111ffffa1111aaaaaaaa111aaaaa111fa1111111fffff1111111111111111fffffffffff
    ffffffffffffaaaaaa9aaa111aaaaaaaaa111fa111affffffffffffffffff111ffffffffffffffff111111ff1111ffaa11119aaaaaaa111111aa111fa1111111111fff11111111111111ffffffffffff
    ffffffffffffaaaaaaaaaa111aaaaaaaaa111aa111aafffffffffffffffff1111fffffffffffffff111111ff1111ffaa1111aaaaaaaa11111111111aa1111111111fff11111111111111ffffffffffff
    ffffffffffffaaaaaaaaaa111111111111111aa111aafffffffffffffffff11111ffffffffffffff1111111ff111ffaa1111aaaaaaaa11111111111aa111a111111fff1111111fffffffffffffffffff
    fffffffffffffaaaaaaaaa111111111111111aa111aafffffffffffffffff1111111ffffffffffff1111111ff111fffa1111aaaaaaaa11111111111aa111aaffffffff11111111ffffffffffffffffff
    ffaaaffffaaaa9aaaaaaaa111111111111111aa11111111111ffffffffffaa11111111ffffffffff1111111ff111aaa91111aaaaaaaa111aaaaaaaaaa111affaafffff111f1111aaaaffffffffffffff
    faaaaaffaaaaaaaaaaaaaa1111111aaaaaaaaaa11111111111fffffffffaaaa111111111ffffffff111a1111f111aaaa1111aaaaaaaa111aaaaaaaaaa111afaaaaffff111ff1111aaaafffffffffffff
    faaaaafaaaaaaaaaaaaaaa1111111aaaaaaaaaa11111111111fffffffffaaaaaaf11111111ffffff111a1111f1111aaa1111aaaaaaaa111aaaaaaaaaa111afaaaaffff111ff1111aaaafaaafffffffff
    ffaaaaaaaaaaaaaaaaaaaa111a1111aaaaaaaaa111aaaaaafffffffffffffaaaaaa11111111fffff111fa111a1111aaa1111aaaaaaaa111aaaaaaaaaa111aaaaaaffff111fff111aaaaaaaaaffffffff
    faaaaaaaaaaaaaaaaaaaaa111a11111aaaaaaaa111aaaaafffffffffaaaafaaaaaaaa1111111ffff111aa1111a111aaa111aaaaaaaaa111aaaaaaaaa1111aaaaafffff111faa1111aaaaaaaaffffffff
    aaaaaaaaaaaaaaaaaaaaaa111aa1111aaaaaaaa111aaaaaafffffffaaaaaaaaaaaaaaff111111ff1111aa11111111aaa111aaaaaaaaa111aaaaaaaaa1111aaaaaaffff111aaa1111aaaaaaafffffffff
    aaaaaaaaaaaaaaaaaaaaaa111aaa1111aaaaaaa111aaaaaaafaaaffaaaaaaaaaaaaaaaaaa1111ffd111aaa1111111daa111aaaaaaaaa111aaaaaaaaa111aaaaaaaafaa111aaaa1111aaaaaaaaaafffff
    aaaaaaaaaaaaaaaaaaaaaa111aaa11111aaaaaa111aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa111f1d111aaa1111111daa111aaaaaaaaa111aaaaaaaaa111aaaaaaaaaaa111aaaa11111aaaaaaaaaaffff
    aaaaaaaaaaaaaaaaaaaaaa111aaaa11111aaaaa111aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa111ddd111daaa111111dda111aaaaaaaaa111aaaaaaaaa1111aaaaaaaaaa111aaaaa11111aaaaaaaaaffff
    aaaaaaaaaaaaaaaaaaaaaa111aaaaa1111aaaaa111ddddddddaaaa11111aaaaaaaaaaaaaa1111ddd111daaaa11111dd1111111111aaa111aaaaaaaaa1111111111aaaa111dddddd1111aaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaa111aaaaaa1111aaaa111ddddddddaaaa11111aaaaaaaaaaaa111111ddd111daaaaa1111dd1111111111aaa111aaaaaaaaa1111111111aaaa111dddddd1111aaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaddd111aaaaaa11111aaa11111ddddddaaaa11111aaaaa111aaa1111111d11111daaaaad111dd1111111111aaa111aaaaaddaaa111111111aaaa111dd1d1dd111aaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaadddd111aaaaaaa1111aaa111111111111aaa11111aaaaa11111111111aadddddddaaaaadddddddaaaaaaaaaaaaaaaaaaaddddaa11111aaaaaaaa111dddddd1111aaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaddddd111aaaaaaaa111aaa111111111111aaa11111adaaa1111111111aaad1dddddaaaaadddddddaaaaaaaaaaaaaaaaaddddddaa111aaaaaaaaaa111ddddddddddaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaddd1d111aaadaaaaaaaaaa111111111111aaaaaaaaddaaa111111111daaadddddddaaaaadddddddaaaaaaaaaaaaaaaaaddd1daaaaaaddaaaaaaaaaaadddd1dddddaaaaaaaaddaaa
    aaaaaaaaaaaaaaaaaddddddaaaaadaaaaaaaaaaaaddddddd1daaaaaaaaaddaaaaaaaadddddaaadddddddaaaaadddddddaaaaaaaaaaaaaaaaaddddddaaaaaddaaaaaaaaaaaddddddd1ddaaaaaaaaddaaa
    aaaaaaaadddaaaaaadd11daaaaadddaaaaaaaaaaadddddddddaaddddddaddaaaaaaaadddddaaadddddddaaaaadddddddaaaaaaaaaddaaaaaaddd1daaaaadddaaaaaaaaaaaddddddddddadddddddddaaa
    daddaaaaddddddddddd1dddaaadddddaaaaaaaaaaddddddd1daad11dddaddaaaaaaaaadd1ddaadddddddaaaddddddddddaddaaaaddddddddddddd1daaaaddddaaaaaaaaaadddddd11ddad11ddddddaaa
    ddddaaaaad1dd1dddddddddaaadddddaaaaaaaaaadddddddddaadddd1daddaaaaaaaaddddddaadd1ddddaaadddddddddddddaaaadd1ddd1ddddddddaaaaddddaaaaaaaaaaddddddddddadddd1ddddaaa
    dd1daaaaaddd1111dddddddaaadddddaaaaaaaaaadddddddddaadddd1ddddaaaaaaaaddddddaadddddddaaaddddddddddd1daaaadddd1d11dddddddaaaaddddaaaaaaaaaaddddddddddadddd1ddddaaa
    ddddaaaaddddddddddddddddaaddddddaaddaddadddddddddddad11ddddddaaaaaaaaddddddaadddddddaaadddddddddddddaaaaddddddddddddddddaaddddddaaadaadddddddddddddad11ddddddaaa
    dd1daaaaddddddddddddddddaaddddddaadddddddddddddddddadddddddddaadaadaaddddddaadddddddaaaddddddddddd1daaaaddddddddddddddddaaddddddaaaddddddddddddddddadddddddddaaa
    dddddadd1d1dddddddddddddaadddddddadddd11ddddddddddddd11aadddddddadddaadd1ddaadddddddaaadddddddddddddddaddd1dddddddddddddaadddddddaaad11ddddddaddddddd11aaadddadd
    dddddadddddddddddddddddddd1ddddddadddddddddaaadddddddddaaaddddddadddaddddddaadddddddaaadddddddddddddddaddddddddddddddddddddddddddaddddddddddaadddddddddaaadddadd
    dddddadddddddddddddddddddddddddddadddddddddaaadddddddddaaaddddddddddddddddddddddddddaaadddddddddddddddaddddddddddddddddddddddddddaddddddddddaadddddddddaaadddddd
    dddddadddddddddddddddddddddddddddadddddddaaaaaaaddddddaaaaadddddddddddddddddddddddddddadddddddddddddddaddddddddddddddddddddddddddad1ddddddaaaaaaadddddaaaaaddddd
    dddddaaaaaaaaadddddddddddddddddddadddddddaaaaaaaddddddaaaaadddddddddddddddddddddddddddaddddddddddddddaaaaaaaaaaddddddddddddddddddaddddddddaaaaaaadddddaaaaaddddd
    dddddaaaaaaaaadddddddddddddddddddadddddddaaaaaaaddddddaaaaadddddddddddddddddddddddddddaddddddddddddddaaaaaaaaaaddddddddddddddddddaddddddddaaaaaaadddddaaaaaddddd
    dddddaddaaaaaadddddddddddddddddddadddddddaddaaaadddddaaaaaaadd111dddddddddddddddaaddddaddddddddddddddaadadaaaaaddddddddddddddddddaddddddddaaaaaaaddddaaaaaaaa11d
    dddddaaaaaaadadddddddddddddddddddadddddddaaaaaaadddddaaaaaaaddd11ddddddddddddddaaaadddaddddddddddddddaaaaaaddaaddddddddddddddddddaddddddddaaaaaaaddddaaaaaaaaddd
    dddddaaaaaaaaaddddddddddaddddddddaaaaadddadaaaaadddddaaaaaaaddddddddddd1dddddaaaaaadddaddddddddddddddaaaaaaaaaadddddddddddddddddddaaaaddddaaadaaaddddaaaaaaaaddd
    dddddaaaaaaaaadddddddddaaddddddddaaaaadddaaaaaaadddddaaaaaaadd1ddddddddddddddaaadaddddddaadddddddddddaaaadaaaaaddddddddaadddddddddaaaaddddaaadaaaddddaaaaaaaad1d
    dddddaaaaaaadadddddddddaaddddddddaaaaadddaaaaaaadddddaaaaaaadd111ddddddddddddaaaaaadddddaadddddddddddaaaaaaadaaddddddddaaddddddddaaaaaadddaaaaaaaddddaaaaaaaa11d
    dddddaaaaaaaaaddaaaaaadaaddddddddaaaaadddaaaaaaadddddaaaaaaadddddddddaa1dddddaaadadddddaaadddddddddddaaaaaaaaaadaaaaaaaaaddddddddaaaaaadddaaadaaaddddaaaaaaaaddd
    dddddaaaaaaadaddaddaaadaadddddddddaadaaddaaaaaaadddaaaaaaaaaadaaddddaaaaaaaaaaaaadaddddaaaaddddddddddaaaaaaddaadaddaaaaaaddddddddaaaaaaaddaaaaaaaddaaaaaaaaaaaaa
    dddddaaaaaaaaaddaaaadadaaddddddddaaaaaaddaadaaaadddaaaaaaaaaaaaaddddaadaaadaaaaaaaaddddaaaaddddddddddaaaaaaaaaadaaaadaaaaddddddddaaaaaaaddaaaadaaddaaaaaaaaaaaaa
    dddddaaaaaaaaaddaaaadaaaaddddddddaaaaaaddaaaaaaadddaaaaaaaaaaadaddddaaaadaddaaaaaaaddddaaaaddddddddddaaaaaaaaaadaaaadaaaaddddddddaaaaaaaddaaaaaaaddaaaaaaaaaaaaa
    daadaaaaaaaaaaadaddaaaaaaddddddddaaaaaaddaaaaaaadddaaaaaaaaaaaaaddddaaaaaaaaaaaaaaaaddaaaaaadddaddaaaaaaaaaaaaadaddaaaaaaddddddddaaaaaaaddaaaaaaaddaaaaaaaaaaaaa
    aaaaaaaaaaaaaaadaaaaaaaaaddaddaddaaaaaaddaaaaaaadddaaaaaaaaaaadaddddaaaaaaaaaaaaaaaaddaaaaaadddaaaaaaaaaaaaaaaadaaaaaaaaadddddaddaaaaaaaddaaaaaaaddaaaaaaaaaaaaa
    aaddaaaaaaaaaaaaaddddaaaaaaadaaaddaadaaddaaaaaaadddaaaaaaaaaaaaaaadaaadaaaaaaaaaaaaaddaaaaaaadddaddaaaaaaaaaaaaaaddadaaaadaadaaadaaaaaaaddaaaaaaaddaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaadaaadaaaaaaddaaaaaaadddaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaadaadaaaaaaaaaaaddaaaadaaddaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaddaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaadadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaadddaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaddadadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaddaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaadddaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaddadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaacaaaaa
    aaaaaacaaaccaaaaaccaaaacaaacaaaacaccaaacaaaaaacaaaccaaaaaccaaaacaaacaaaacaccaaacaaaaaacaaaccaaaaaccaaaacaaacaaaacaccaaacaaaaaacaaaccaaaaaccaaaacaaacaaaacaccaaac
    aacaaaccaccaacaaaccaaaccaaaccaaacaaccaccaacaaaccaccaacaaaccaaaccaaaccaaacaaccaccaacaaaccaccaacaaaccaaaccaaaccaaacaaccaccaacaaaccaccaacaaaccaaaccaaaccaaacaaccacc
    aaccaaccaccaaccaaaccaccaaaaccacaccaccccaaaccaaccaccaaccaaaccaccaaaaccacaccaccccaaaccaaccaccaaccaaaccaccaaaaccacaccaccccaaaccaaccaccaaccaaaccaccaaaaccacaccaccccb
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    `)
let start = sprites.create(img`
    ................................
    .11111..11111..111...11111.11111
    .1........1...1...1..1...1...1..
    .1........1...1...1..1...1...1..
    .1........1...1...1..11111...1..
    .11111....1...1...1..11......1..
    .....1....1..1111111.1.1.....1..
    .....1....1..1.....1.1..1....1..
    .....1....1..1.....1.1...1...1..
    .11111....1..1.....1.1...1...1..
    ................................
    `, SpriteKind.Enemy)
start.setPosition(80, 95)
let Sniper = sprites.create(img`
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    f f f f f f . 2 . f f f f f f f 
    . . . . . . . . . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    . . . . . . . f . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Sniper, 100, 100)
multilights.addLightSource(Sniper, 13)
multilights.toggleLighting(true)
